### ISSUE TITLE
Bug in ExportGGPK project

### ISSUE THREAD

**Issue by zaafar** [MuxaJIbI4/libggpk#13]
```
C:\Users\Zaafar Ahmed\Desktop\development-work\libggpk\ExportGGPK\bin\Release>ExportGGPK.exe "C:\Program Files (x86)\Grinding Gear Games\Path of Exile\Content.ggpk" "C:\Users\Zaafar Ahmed\Desktop\development-work\libggpk\ExportGGPK\bin\Release\base_output_dir" "C:\Users\Zaafar Ahmed\Desktop\development-work\libggpk\ExportGGPK\bin\Release\data_dir"
Parsing GGPK...
Reading GGPK file records:
        10.00%
        20.00%
        30.01%
        40.01%
        50.01%
        60.01%
        70.08%
        80.10%
        90.17%
        100.00%

Building directory tree...
Found 30794 directories and 458698 files
Found 463 FREE records

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at ExportGGPK.Program.WalkNode(DirectoryTreeNode start, String subDirectory) in C:\Users\Zaafar Ahmed\Desktop\development-work\libggpk\ExportGGPK\Program.cs:line 67
   at ExportGGPK.Program.GetDirectory(String path) in C:\Users\Zaafar Ahmed\Desktop\development-work\libggpk\ExportGGPK\Program.cs:line 57
   at ExportGGPK.Program.Main(String[] args) in C:\Users\Zaafar Ahmed\Desktop\development-work\libggpk\ExportGGPK\Program.cs:line 36
```

**Comment by zaafar** [comment]
nevermind, looks like "data dir" arg is the Directory inside the content.ggpk which you want to extract.
