### ISSUE TITLE
Error in three Dat

### ISSUE THREAD

**Issue by aianlinb** [MuxaJIbI4/libggpk#21]
Details: Failed to read dat: Error: Row ID = 1393 Field Id=Unknown9, Field Type Name = ref|string,
 Message:無法讀取資料流末端之外。
 Stacktrace:    at System.IO.BinaryReader.ReadChar()
   at LibDat.Types.TypeFactory.<>c.<.cctor>b__12_8(BinaryReader s) at C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: Line 36
   at LibDat.Types.TypeFactory.Read[T](BinaryReader reader) at C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: Line 68
   at LibDat.Data.ValueData`1..ctor(BaseDataType type, BinaryReader reader, Dictionary`2 options) at C:\Users\tpo\Downloads\libggpk3\LibDat\Data\ValueData.cs: Line 28
   at LibDat.Data.StringData..ctor(BaseDataType type, BinaryReader inStream, Dictionary`2 options) at C:\Users\tpo\Downloads\libggpk3\LibDat\Data\StringData.cs: Line 19
   at LibDat.Types.TypeFactory.CreateData(BaseDataType type, BinaryReader inStream, Dictionary`2 options) at C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: Line 234
   at LibDat.Data.PointerData..ctor(PointerDataType dataType, BinaryReader reader, Dictionary`2 options) at C:\Users\tpo\Downloads\libggpk3\LibDat\Data\PointerData.cs: Line 34
   at LibDat.Types.TypeFactory.CreateData(BaseDataType type, BinaryReader inStream, Dictionary`2 options) at C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: Line 203
   at LibDat.FieldData..ctor(FieldInfo fieldInfo, BinaryReader reader) at C:\Users\tpo\Downloads\libggpk3\LibDat\FieldData.cs: Line 27
   at LibDat.RecordData..ctor(RecordInfo ri, BinaryReader inStream, Int32 index) at C:\Users\tpo\Downloads\libggpk3\LibDat\RecordData.cs: Line 36

----------------------------------------------------------------------------------------------

Details: Failed to read dat: Error: Row ID = 128 Field Id=RestrictedAreaMessage, Field Type Name = ref|string,
 Message:無法讀取資料流末端之外。
 Stacktrace:    at System.IO.BinaryReader.ReadChar()
   at LibDat.Types.TypeFactory.<>c.<.cctor>b__12_8(BinaryReader s) at C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: Line 36
   at LibDat.Types.TypeFactory.Read[T](BinaryReader reader) at C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: Line 68
   at LibDat.Data.ValueData`1..ctor(BaseDataType type, BinaryReader reader, Dictionary`2 options) at C:\Users\tpo\Downloads\libggpk3\LibDat\Data\ValueData.cs: Line 28
   at LibDat.Data.StringData..ctor(BaseDataType type, BinaryReader inStream, Dictionary`2 options) at C:\Users\tpo\Downloads\libggpk3\LibDat\Data\StringData.cs: Line 19
   at LibDat.Types.TypeFactory.CreateData(BaseDataType type, BinaryReader inStream, Dictionary`2 options) at C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: Line 234
   at LibDat.Data.PointerData..ctor(PointerDataType dataType, BinaryReader reader, Dictionary`2 options) at C:\Users\tpo\Downloads\libggpk3\LibDat\Data\PointerData.cs: Line 34
   at LibDat.Types.TypeFactory.CreateData(BaseDataType type, BinaryReader inStream, Dictionary`2 options) at C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: Line 203
   at LibDat.FieldData..ctor(FieldInfo fieldInfo, BinaryReader reader) at C:\Users\tpo\Downloads\libggpk3\LibDat\FieldData.cs: Line 27
   at LibDat.RecordData..ctor(RecordInfo ri, BinaryReader inStream, Int32 index) at C:\Users\tpo\Downloads\libggpk3\LibDat\RecordData.cs: Line 36

----------------------------------------------------------------------------------------------

Details: Failed to read dat: Error: Row ID = 0 Field Id=QuestFinished_OGGFile, Field Type Name = ref|string,
 Message:Not found int(0) value at the end of the string
 Stacktrace:    at LibDat.Types.TypeFactory.<>c.<.cctor>b__12_8(BinaryReader s) at C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: Line 39
   at LibDat.Types.TypeFactory.Read[T](BinaryReader reader) at C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: Line 68
   at LibDat.Data.ValueData`1..ctor(BaseDataType type, BinaryReader reader, Dictionary`2 options) at C:\Users\tpo\Downloads\libggpk3\LibDat\Data\ValueData.cs: Line 28
   at LibDat.Data.StringData..ctor(BaseDataType type, BinaryReader inStream, Dictionary`2 options) at C:\Users\tpo\Downloads\libggpk3\LibDat\Data\StringData.cs: Line 19
   at LibDat.Types.TypeFactory.CreateData(BaseDataType type, BinaryReader inStream, Dictionary`2 options) at C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: Line 234
   at LibDat.Data.PointerData..ctor(PointerDataType dataType, BinaryReader reader, Dictionary`2 options) at C:\Users\tpo\Downloads\libggpk3\LibDat\Data\PointerData.cs: Line 34
   at LibDat.Types.TypeFactory.CreateData(BaseDataType type, BinaryReader inStream, Dictionary`2 options) at C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: Line 203
   at LibDat.FieldData..ctor(FieldInfo fieldInfo, BinaryReader reader) at C:\Users\tpo\Downloads\libggpk3\LibDat\FieldData.cs: Line 27
   at LibDat.RecordData..ctor(RecordInfo ri, BinaryReader inStream, Int32 index) at C:\Users\tpo\Downloads\libggpk3\LibDat\RecordData.cs: Line 36

**Comment by Chuanhsing** [comment]
Updated Libggpk specs to 3.9.1
